"""Texte der Team-Seite ({ordner}team/), je Sprache ein Block.

Die Seite hat zwei Aufgaben: Ohne Vorlage im Link erklaert sie StartWork im
Team; mit "#v1..." zeigt sie oben die geteilte Team-Vorlage und oeffnet sie
in der App. Knopfnamen wie "Team-Vorlage uebernehmen" muessen woertlich so
lauten wie in der App (Katalog in StartWork/index.html) - sonst sucht man
in der App nach etwas, das dort anders heisst.

{n} in rundung_min wird im Browser ersetzt.
"""

TEAM = {
    'en': dict(
        titel='StartWork for teams – team template and MDM deployment',
        beschreibung='Set it up once, share it as a link: Jira address, tiles and rules for the whole team. No token in the link. Deployable through device management.',
        h1='StartWork for teams',
        lead='Everyone logs time with their own Jira access – and the team is still set up in a minute. No server, no account, no subscription.',
        vorlage_titel='Team template',
        vorlage_einleitung='Someone on your team set up StartWork and is sharing the settings with you.',
        adresse='Jira address', kacheln='Tiles', rundung='Rounding', rundung_exakt='Exact', rundung_min='{n} min',
        ki='AI polishing', ki_an='allowed', ki_aus='off for the team',
        schritt_laden='1. Get StartWork, if you haven’t yet.',
        schritt_oeffnen='2. Open the template. StartWork first shows you what it will apply – then you only enter your own token.',
        oeffnen='Open in StartWork',
        ausweich='Nothing opens? In StartWork, go to Settings → Team → “Use a team template” and paste this link.',
        kopieren='Copy link', kopiert='Copied',
        ungueltig='This link doesn’t contain a valid team template. Ask the person who shared it for a new one.',
        vorlage_privat='The template sits in the link after the #. That part is never sent to a server – this page only reads it in your browser.',
        so_titel='How to set up your team',
        so=[
            'One person sets up StartWork: Jira address, tiles for your tickets, rounding.',
            'Settings → Team → “Share team template” creates a link – for your team chat, say.',
            'Whoever opens the link sees what will be applied, confirms, and enters their own token. Done.',
        ],
        link_titel='What’s in the link – and what isn’t',
        link_drin='In it: Jira address, tiles (ticket, title, customer, color), rounding, and whether AI polishing is allowed.',
        link_nicht='Not in it: token, email, AI key, worklogs. If a link points to a different Jira address than before, StartWork deletes the stored token – it never goes to a foreign address.',
        it_titel='For IT: deploy with device management',
        it_kauf='Buy licenses in bulk in Apple Business under “Apps and Books” and assign them to devices or people through your device management (MDM).',
        it_konfig='With managed app configuration you can preset two values for StartWork:',
        it_vorlage='Link to a team template (string). StartWork applies it at launch without asking – once per change; after that, people may adjust their tiles.',
        it_kiaus='true (boolean) turns AI polishing off. It can’t be switched on in the app, and nothing is sent to Anthropic.',
        it_token='Everyone enters their own Jira token. It stays in the iPhone’s keychain and only goes to your Jira.',
        kontakt_titel='Questions or requests for your team?',
        kontakt_text='Want to roll out StartWork in your team, or missing something? Write to',
        mehr='More about StartWork',
    ),
    'de': dict(
        titel='StartWork im Team – Team-Vorlage und Verteilung per MDM',
        beschreibung='Einmal einrichten, als Link teilen: Jira-Adresse, Kacheln und Regeln fürs ganze Team. Kein Token im Link. Verteilung per Geräteverwaltung möglich.',
        h1='StartWork im Team',
        lead='Jede Person bucht mit dem eigenen Jira-Zugang – eingerichtet ist das Team trotzdem in einer Minute. Kein Server, kein Konto, kein Abo.',
        vorlage_titel='Team-Vorlage',
        vorlage_einleitung='Jemand aus deinem Team hat StartWork eingerichtet und teilt die Einstellungen mit dir.',
        adresse='Jira-Adresse', kacheln='Kacheln', rundung='Rundung', rundung_exakt='Exakt', rundung_min='{n} Min',
        ki='KI-Formulierung', ki_an='erlaubt', ki_aus='im Team aus',
        schritt_laden='1. StartWork laden, falls noch nicht geschehen.',
        schritt_oeffnen='2. Vorlage öffnen. StartWork zeigt dir vorher, was übernommen wird – danach trägst du nur noch deinen eigenen Token ein.',
        oeffnen='In StartWork öffnen',
        ausweich='Öffnet sich nichts? In StartWork unter Einstellungen → Team → „Team-Vorlage übernehmen“ diesen Link einfügen.',
        kopieren='Link kopieren', kopiert='Kopiert',
        ungueltig='Dieser Link enthält keine gültige Team-Vorlage. Bitte die Person, die ihn geteilt hat, um einen neuen.',
        vorlage_privat='Die Vorlage steht im Link hinter dem #. Dieser Teil wird nie an einen Server geschickt – diese Seite liest ihn nur in deinem Browser.',
        so_titel='So richtet ihr das Team ein',
        so=[
            'Eine Person richtet StartWork ein: Jira-Adresse, Kacheln für eure Tickets, Rundung.',
            'Unter Einstellungen → Team → „Team-Vorlage teilen“ entsteht ein Link – etwa für euren Team-Chat.',
            'Wer den Link öffnet, sieht vorher, was übernommen wird, bestätigt und trägt den eigenen Token ein. Fertig.',
        ],
        link_titel='Was im Link steckt – und was nicht',
        link_drin='Drin: Jira-Adresse, Kacheln (Ticket, Titel, Kunde, Farbe), Rundung und ob die KI-Formulierung erlaubt ist.',
        link_nicht='Nicht drin: Token, E-Mail, KI-Schlüssel, Buchungen. Zeigt ein Link auf eine andere Jira-Adresse als bisher, löscht StartWork den gespeicherten Token – er geht nie an eine fremde Adresse.',
        it_titel='Für die IT: verteilen per Geräteverwaltung',
        it_kauf='Lizenzen kauft ihr gesammelt in Apple Business unter „Apps und Bücher“ und weist sie über eure Geräteverwaltung (MDM) Geräten oder Personen zu.',
        it_konfig='Über die verwaltete App-Konfiguration gebt ihr StartWork zwei Werte vor:',
        it_vorlage='Link einer Team-Vorlage (Text). StartWork übernimmt ihn beim Start ohne Rückfrage – einmal je Änderung; danach dürfen die Leute ihre Kacheln selbst anpassen.',
        it_kiaus='true (Wahrheitswert) schaltet die KI-Formulierung ab. Sie lässt sich dann in der App nicht einschalten, und es geht nichts an Anthropic.',
        it_token='Den Jira-Token trägt jede Person selbst ein. Er liegt im Schlüsselbund des iPhones und geht nur an euer Jira.',
        kontakt_titel='Fragen oder Wünsche fürs Team?',
        kontakt_text='Ihr wollt StartWork im Team einführen oder braucht etwas, das fehlt? Schreibt an',
        mehr='Mehr über StartWork',
    ),
    'fr': dict(
        titel='StartWork en équipe – modèle d’équipe et déploiement MDM',
        beschreibung='Configurez une fois, partagez un lien : adresse Jira, tuiles et règles pour toute l’équipe. Aucun jeton dans le lien. Déploiement possible via la gestion des appareils.',
        h1='StartWork en équipe',
        lead='Chacun saisit son temps avec son propre accès Jira – et l’équipe est configurée en une minute. Pas de serveur, pas de compte, pas d’abonnement.',
        vorlage_titel='Modèle d’équipe',
        vorlage_einleitung='Une personne de votre équipe a configuré StartWork et partage ses réglages avec vous.',
        adresse='Adresse Jira', kacheln='Tuiles', rundung='Arrondi', rundung_exakt='Exact', rundung_min='{n} min',
        ki='Rédaction IA', ki_an='autorisée', ki_aus='désactivée pour l’équipe',
        schritt_laden='1. Installez StartWork, si ce n’est pas encore fait.',
        schritt_oeffnen='2. Ouvrez le modèle. StartWork vous montre d’abord ce qui sera appliqué – il ne reste qu’à saisir votre propre jeton.',
        oeffnen='Ouvrir dans StartWork',
        ausweich='Rien ne s’ouvre ? Dans StartWork, allez dans Réglages → Équipe → « Utiliser un modèle d’équipe » et collez ce lien.',
        kopieren='Copier le lien', kopiert='Copié',
        ungueltig='Ce lien ne contient pas de modèle d’équipe valide. Demandez-en un nouveau à la personne qui l’a partagé.',
        vorlage_privat='Le modèle se trouve dans le lien, après le #. Cette partie n’est jamais envoyée à un serveur – cette page la lit uniquement dans votre navigateur.',
        so_titel='Configurer l’équipe',
        so=[
            'Une personne configure StartWork : adresse Jira, tuiles pour vos tickets, arrondi.',
            'Réglages → Équipe → « Partager le modèle d’équipe » crée un lien – pour la discussion de l’équipe, par exemple.',
            'Qui ouvre le lien voit d’abord ce qui sera appliqué, confirme et saisit son propre jeton. C’est tout.',
        ],
        link_titel='Ce que contient le lien – et ce qu’il ne contient pas',
        link_drin='Dedans : adresse Jira, tuiles (ticket, titre, client, couleur), arrondi et si la rédaction IA est autorisée.',
        link_nicht='Pas dedans : jeton, e-mail, clé IA, saisies de temps. Si un lien pointe vers une autre adresse Jira qu’avant, StartWork supprime le jeton enregistré – il ne part jamais vers une adresse étrangère.',
        it_titel='Pour l’IT : déployer via la gestion des appareils',
        it_kauf='Achetez les licences en volume dans Apple Business, rubrique « Apps et livres », et attribuez-les aux appareils ou aux personnes via votre gestion des appareils (MDM).',
        it_konfig='La configuration d’app gérée permet d’imposer deux valeurs à StartWork :',
        it_vorlage='Lien d’un modèle d’équipe (chaîne). StartWork l’applique au lancement sans demander – une fois par modification ; ensuite, chacun peut adapter ses tuiles.',
        it_kiaus='true (booléen) désactive la rédaction IA. Elle ne peut alors pas être activée dans l’app, et rien n’est envoyé à Anthropic.',
        it_token='Chacun saisit son propre jeton Jira. Il reste dans le trousseau de l’iPhone et ne va qu’à votre Jira.',
        kontakt_titel='Des questions ou des besoins pour l’équipe ?',
        kontakt_text='Vous voulez déployer StartWork dans votre équipe, ou il vous manque quelque chose ? Écrivez à',
        mehr='En savoir plus sur StartWork',
    ),
    'pt': dict(
        titel='StartWork em equipe – modelo de equipe e distribuição por MDM',
        beschreibung='Configure uma vez e compartilhe um link: endereço do Jira, blocos e regras para toda a equipe. Sem token no link. Distribuição possível pelo gerenciamento de dispositivos.',
        h1='StartWork em equipe',
        lead='Cada pessoa registra horas com o próprio acesso ao Jira – e a equipe fica configurada em um minuto. Sem servidor, sem conta, sem assinatura.',
        vorlage_titel='Modelo de equipe',
        vorlage_einleitung='Alguém da sua equipe configurou o StartWork e está compartilhando as configurações com você.',
        adresse='Endereço do Jira', kacheln='Blocos', rundung='Arredondamento', rundung_exakt='Exato', rundung_min='{n} min',
        ki='Refinamento por IA', ki_an='permitido', ki_aus='desativado na equipe',
        schritt_laden='1. Baixe o StartWork, se ainda não tiver.',
        schritt_oeffnen='2. Abra o modelo. O StartWork mostra antes o que será aplicado – depois é só informar o seu próprio token.',
        oeffnen='Abrir no StartWork',
        ausweich='Nada abriu? No StartWork, vá em Ajustes → Equipe → “Usar um modelo de equipe” e cole este link.',
        kopieren='Copiar link', kopiert='Copiado',
        ungueltig='Este link não contém um modelo de equipe válido. Peça um novo a quem o compartilhou.',
        vorlage_privat='O modelo fica no link, depois do #. Essa parte nunca é enviada a um servidor – esta página só a lê no seu navegador.',
        so_titel='Como configurar a equipe',
        so=[
            'Uma pessoa configura o StartWork: endereço do Jira, blocos para os seus tickets, arredondamento.',
            'Em Ajustes → Equipe → “Compartilhar modelo de equipe” surge um link – para o chat da equipe, por exemplo.',
            'Quem abre o link vê antes o que será aplicado, confirma e informa o próprio token. Pronto.',
        ],
        link_titel='O que vai no link – e o que não vai',
        link_drin='Vai: endereço do Jira, blocos (ticket, título, cliente, cor), arredondamento e se o refinamento por IA é permitido.',
        link_nicht='Não vai: token, e-mail, chave de IA, registros de trabalho. Se um link aponta para um endereço do Jira diferente do anterior, o StartWork apaga o token salvo – ele nunca vai para um endereço estranho.',
        it_titel='Para a TI: distribuir pelo gerenciamento de dispositivos',
        it_kauf='Compre licenças em volume no Apple Business, em “Apps e Livros”, e atribua-as a dispositivos ou pessoas pelo gerenciamento de dispositivos (MDM).',
        it_konfig='Com a configuração de app gerenciada, você define dois valores para o StartWork:',
        it_vorlage='Link de um modelo de equipe (string). O StartWork o aplica ao abrir, sem perguntar – uma vez a cada mudança; depois, cada pessoa pode ajustar os próprios blocos.',
        it_kiaus='true (booleano) desativa o refinamento por IA. Ele não pode ser ativado no app, e nada é enviado à Anthropic.',
        it_token='Cada pessoa informa o próprio token do Jira. Ele fica nas Chaves do sistema do iPhone e só vai para o seu Jira.',
        kontakt_titel='Dúvidas ou pedidos para a equipe?',
        kontakt_text='Quer adotar o StartWork na sua equipe ou sente falta de algo? Escreva para',
        mehr='Mais sobre o StartWork',
    ),
    'es': dict(
        titel='StartWork en equipo – plantilla de equipo y despliegue por MDM',
        beschreibung='Configúralo una vez y compártelo como enlace: dirección de Jira, mosaicos y reglas para todo el equipo. Sin token en el enlace. Se puede desplegar con la gestión de dispositivos.',
        h1='StartWork en equipo',
        lead='Cada persona registra su tiempo con su propio acceso a Jira – y el equipo queda configurado en un minuto. Sin servidor, sin cuenta, sin suscripción.',
        vorlage_titel='Plantilla de equipo',
        vorlage_einleitung='Alguien de tu equipo ha configurado StartWork y comparte los ajustes contigo.',
        adresse='Dirección de Jira', kacheln='Mosaicos', rundung='Redondeo', rundung_exakt='Exacto', rundung_min='{n} min',
        ki='Pulido con IA', ki_an='permitido', ki_aus='desactivado en el equipo',
        schritt_laden='1. Descarga StartWork, si aún no lo tienes.',
        schritt_oeffnen='2. Abre la plantilla. StartWork te muestra antes qué se aplicará – después solo introduces tu propio token.',
        oeffnen='Abrir en StartWork',
        ausweich='¿No se abre nada? En StartWork, ve a Ajustes → Equipo → «Usar una plantilla de equipo» y pega este enlace.',
        kopieren='Copiar enlace', kopiert='Copiado',
        ungueltig='Este enlace no contiene una plantilla de equipo válida. Pide uno nuevo a quien lo compartió.',
        vorlage_privat='La plantilla va en el enlace, detrás del #. Esa parte nunca se envía a un servidor – esta página solo la lee en tu navegador.',
        so_titel='Cómo configurar el equipo',
        so=[
            'Una persona configura StartWork: dirección de Jira, mosaicos para vuestros tickets, redondeo.',
            'En Ajustes → Equipo → «Compartir plantilla de equipo» se crea un enlace – para el chat del equipo, por ejemplo.',
            'Quien abre el enlace ve antes qué se aplicará, confirma e introduce su propio token. Listo.',
        ],
        link_titel='Qué lleva el enlace – y qué no',
        link_drin='Lleva: dirección de Jira, mosaicos (ticket, título, cliente, color), redondeo y si se permite el pulido con IA.',
        link_nicht='No lleva: token, correo, clave de IA, registros de trabajo. Si un enlace apunta a una dirección de Jira distinta de la anterior, StartWork borra el token guardado – nunca va a una dirección ajena.',
        it_titel='Para TI: desplegar con la gestión de dispositivos',
        it_kauf='Compra licencias por volumen en Apple Business, en «Apps y libros», y asígnalas a dispositivos o personas con tu gestión de dispositivos (MDM).',
        it_konfig='Con la configuración de apps gestionada puedes fijar dos valores para StartWork:',
        it_vorlage='Enlace de una plantilla de equipo (cadena). StartWork la aplica al abrirse sin preguntar – una vez por cada cambio; después, cada persona puede ajustar sus mosaicos.',
        it_kiaus='true (booleano) desactiva el pulido con IA. No se puede activar en la app y no se envía nada a Anthropic.',
        it_token='Cada persona introduce su propio token de Jira. Se guarda en el llavero del iPhone y solo va a tu Jira.',
        kontakt_titel='¿Preguntas o peticiones para el equipo?',
        kontakt_text='¿Quieres implantar StartWork en tu equipo o echas algo en falta? Escribe a',
        mehr='Más sobre StartWork',
    ),
}
