"""Texte der Produktseite, je Sprache ein Block.

Gleiche Schluessel in allen Sprachen - bauen.py bricht ab, wenn einer fehlt.
Formulierungen bewusst nah an den Store-Texten: wer von der Seite in den
Store kommt, soll dort wiederfinden, was ihm hier versprochen wurde.
"""

TEXTE = {
    'en': dict(
        hreflang='en', ordner='', name='English',
        titel='StartWork – Log Jira time from your iPhone',
        beschreibung='Tap a tile, the clock runs. Tap again, describe it in one sentence – logged to Jira. Runs on your device: no account, no cloud, one-time purchase.',
        untertitel='Log Jira time without drama',
        lead='Tap a tile – the clock runs. Tap again, describe what you did in one sentence – it’s in Jira. No account, no cloud, nothing to get approved.',
        preis='One-time purchase · no subscription · iPhone',
        badge_alt='Download on the App Store',
        bilder=['Tiles for your regular tickets', 'A running timer at a glance', 'One sentence, logged – optionally polished by AI', 'Rounding, test mode, Face ID lock'],
        saeulen=[
            ('No account, no cloud', 'StartWork runs on your iPhone. There is no server of ours and no sign-up. Your time goes straight to your own Jira – nowhere else.'),
            ('Pay once', 'One purchase. No subscription, no ads, no data collection, no follow-up costs.'),
            ('Built for people who bill by the hour', 'Consultants, freelancers and agencies: log time the moment you switch tasks, not from memory on Friday.'),
        ],
        funktionen_titel='What it does',
        funktionen=[
            'Tiles for your regular tickets, title fetched from Jira',
            'Add tickets by key or by pasting a Jira link',
            'Rounding to 5 or 15 minutes, if your company wants it',
            'Test mode: see what would be logged before logging for real',
            'Notification while a timer runs, so you don’t forget it',
            'Face ID lock – a Jira token lives on the device',
            'Daily report to share, plus previous days for the stand-up',
            'Optional: polish comments for the client with AI, using your own Anthropic key and only after explicit consent',
        ],
        vorab_titel='Before you buy',
        vorab=[
            'StartWork needs a Jira instance you can sign in to with your own token. Jira Cloud, Server and Data Center are supported.',
            'Time is logged as a standard Jira worklog. If your company uses Tempo with required fields (“Work Attributes”), those fields stay empty.',
        ],
        faq_titel='Questions',
        faq=[
            ('How do I log time in Jira from my iPhone?', 'Install StartWork, enter your Jira address and an API token once, and add your tickets as tiles. Tap a tile to start the clock, tap again to stop, write one sentence – StartWork logs it as a worklog on that ticket.'),
            ('Does it work with Tempo?', 'Yes. StartWork writes standard Jira worklogs, which Tempo reads. Required Tempo fields (“Work Attributes”) are not filled in.'),
            ('Which Jira versions are supported?', 'Jira Cloud (sign-in with email and API token) as well as Jira Server and Data Center (personal access token).'),
            ('What happens to my data?', 'It stays on your iPhone and goes only to your own Jira. No analytics, no tracking, no account with us.'),
            ('Is it a subscription?', 'No. You pay once in the App Store.'),
        ],
        hilfe='Help', datenschutz='Privacy', impressum='Legal notice', kontakt='Contact',
        marke='Jira is a trademark of Atlassian, Tempo a trademark of Tempo ehf. StartWork is not affiliated with these companies.',
        sprache='Language',
    ),
    'de': dict(
        hreflang='de', ordner='de/', name='Deutsch',
        titel='StartWork – Zeit in Jira buchen, vom iPhone aus',
        beschreibung='Kachel antippen, die Uhr läuft. Nochmal tippen, in einem Satz beschreiben – in Jira gebucht. Läuft auf deinem Gerät: kein Konto, keine Cloud, Einmalkauf.',
        untertitel='Zeit in Jira buchen ohne Drama',
        lead='Kachel antippen – die Uhr läuft. Nochmal tippen, in einem Satz sagen, was du gemacht hast – steht in Jira. Kein Konto, keine Cloud, nichts zu beantragen.',
        preis='2,99 € · Einmalkauf · kein Abo · iPhone',
        badge_alt='Im App Store laden',
        bilder=['Kacheln für deine üblichen Tickets', 'Laufende Uhr auf einen Blick', 'Ein Satz, gebucht – auf Wunsch von KI geglättet', 'Rundung, Testmodus, Face-ID-Sperre'],
        saeulen=[
            ('Kein Konto, keine Cloud', 'StartWork läuft auf deinem iPhone. Es gibt keinen Server von uns und keine Anmeldung. Deine Zeiten gehen direkt in dein eigenes Jira – nirgendwo sonst hin.'),
            ('Einmal zahlen', 'Ein Kauf. Kein Abo, keine Werbung, keine Datensammlung, keine Folgekosten.'),
            ('Für alle, die nach Stunden abrechnen', 'Berater, Freelancer, Agenturen: buchen in dem Moment, in dem du die Aufgabe wechselst – nicht freitags aus dem Gedächtnis.'),
        ],
        funktionen_titel='Was die App kann',
        funktionen=[
            'Kacheln für deine üblichen Tickets, Titel kommt aus Jira',
            'Tickets per Schlüssel oder eingefügtem Jira-Link hinzufügen',
            'Rundung auf 5 oder 15 Minuten, wenn deine Firma das so will',
            'Testmodus: sehen, was gebucht würde, bevor wirklich gebucht wird',
            'Mitteilung, solange eine Uhr läuft – damit du sie nicht vergisst',
            'Face-ID-Sperre – auf dem Gerät liegt ein Jira-Token',
            'Tagesbericht zum Teilen, dazu die Vortage fürs Daily',
            'Optional: Kommentare für den Kunden per KI glätten – mit eigenem Anthropic-Schlüssel und nur nach ausdrücklicher Zustimmung',
        ],
        vorab_titel='Bevor du kaufst',
        vorab=[
            'StartWork braucht eine Jira-Instanz, bei der du dich mit eigenem Token anmelden darfst. Unterstützt werden Jira Cloud, Server und Data Center.',
            'Gebucht wird als normales Jira-Worklog. Nutzt deine Firma Tempo mit Pflichtfeldern („Work Attributes“), bleiben diese leer.',
        ],
        faq_titel='Fragen',
        faq=[
            ('Wie buche ich Zeit in Jira vom iPhone aus?', 'StartWork installieren, einmal Jira-Adresse und API-Token eintragen, deine Tickets als Kacheln anlegen. Kachel antippen startet die Uhr, nochmal tippen stoppt sie, einen Satz schreiben – StartWork bucht ihn als Worklog auf das Ticket.'),
            ('Funktioniert das mit Tempo?', 'Ja. StartWork schreibt normale Jira-Worklogs, die Tempo liest. Pflichtfelder von Tempo („Work Attributes“) werden nicht befüllt.'),
            ('Welche Jira-Versionen werden unterstützt?', 'Jira Cloud (Anmeldung mit E-Mail und API-Token) sowie Jira Server und Data Center (persönliches Zugriffstoken).'),
            ('Was passiert mit meinen Daten?', 'Sie bleiben auf deinem iPhone und gehen nur an dein eigenes Jira. Keine Analyse, kein Tracking, kein Konto bei uns.'),
            ('Ist das ein Abo?', 'Nein. Du zahlst einmal im App Store.'),
        ],
        hilfe='Hilfe', datenschutz='Datenschutz', impressum='Impressum', kontakt='Kontakt',
        marke='Jira ist eine Marke von Atlassian, Tempo eine Marke von Tempo ehf. StartWork steht in keiner Verbindung zu diesen Unternehmen.',
        sprache='Sprache',
    ),
    'fr': dict(
        hreflang='fr', ordner='fr/', name='Français',
        titel='StartWork – Saisir son temps Jira depuis l’iPhone',
        beschreibung='Touchez une tuile, le chrono tourne. Touchez encore, décrivez en une phrase – c’est saisi dans Jira. Sur votre appareil : sans compte, sans cloud, achat unique.',
        untertitel='Vos heures Jira, sans détour',
        lead='Touchez une tuile – le chrono tourne. Touchez encore, décrivez en une phrase ce que vous avez fait – c’est dans Jira. Sans compte, sans cloud, rien à faire valider.',
        preis='2,99 € · achat unique · sans abonnement · iPhone',
        badge_alt='Télécharger dans l’App Store',
        bilder=['Des tuiles pour vos tickets habituels', 'Le chrono en cours d’un coup d’œil', 'Une phrase, c’est saisi – peaufinée par l’IA si vous le souhaitez', 'Arrondi, mode test, verrouillage Face ID'],
        saeulen=[
            ('Sans compte, sans cloud', 'StartWork fonctionne sur votre iPhone. Pas de serveur à nous, pas d’inscription. Votre temps va directement dans votre propre Jira – nulle part ailleurs.'),
            ('Un seul achat', 'Un achat. Pas d’abonnement, pas de publicité, pas de collecte de données, pas de frais ultérieurs.'),
            ('Pour ceux qui facturent à l’heure', 'Consultants, freelances, agences : saisissez au moment où vous changez de tâche, pas de mémoire le vendredi.'),
        ],
        funktionen_titel='Ce qu’elle fait',
        funktionen=[
            'Des tuiles pour vos tickets habituels, titre récupéré dans Jira',
            'Ajout de tickets par clé ou en collant un lien Jira',
            'Arrondi à 5 ou 15 minutes, si votre entreprise le souhaite',
            'Mode test : voir ce qui serait saisi avant de saisir pour de vrai',
            'Notification pendant qu’un chrono tourne, pour ne pas l’oublier',
            'Verrouillage Face ID – un jeton Jira est stocké sur l’appareil',
            'Rapport du jour à partager, et les jours précédents pour le point',
            'En option : peaufiner les commentaires pour le client avec l’IA, avec votre propre clé Anthropic et uniquement après consentement explicite',
        ],
        vorab_titel='Avant d’acheter',
        vorab=[
            'StartWork nécessite une instance Jira à laquelle vous pouvez vous connecter avec votre propre jeton. Jira Cloud, Server et Data Center sont pris en charge.',
            'Le temps est saisi comme une saisie de temps Jira standard. Si votre entreprise utilise Tempo avec des champs obligatoires (« Work Attributes »), ils restent vides.',
        ],
        faq_titel='Questions',
        faq=[
            ('Comment saisir du temps dans Jira depuis mon iPhone ?', 'Installez StartWork, indiquez une fois l’adresse de votre Jira et un jeton d’API, puis ajoutez vos tickets en tuiles. Touchez une tuile pour lancer le chrono, touchez encore pour l’arrêter, écrivez une phrase – StartWork l’enregistre comme saisie de temps sur le ticket.'),
            ('Est-ce compatible avec Tempo ?', 'Oui. StartWork écrit des saisies de temps Jira standard, que Tempo lit. Les champs Tempo obligatoires (« Work Attributes ») ne sont pas remplis.'),
            ('Quelles versions de Jira sont prises en charge ?', 'Jira Cloud (connexion par e-mail et jeton d’API) ainsi que Jira Server et Data Center (jeton d’accès personnel).'),
            ('Que deviennent mes données ?', 'Elles restent sur votre iPhone et vont uniquement vers votre propre Jira. Pas de statistiques, pas de suivi, pas de compte chez nous.'),
            ('Est-ce un abonnement ?', 'Non. Vous payez une seule fois dans l’App Store.'),
        ],
        hilfe='Aide', datenschutz='Confidentialité', impressum='Mentions légales', kontakt='Contact',
        marke='Jira est une marque d’Atlassian, Tempo une marque de Tempo ehf. StartWork n’est pas affilié à ces entreprises.',
        sprache='Langue',
    ),
    'pt': dict(
        hreflang='pt-BR', ordner='pt/', name='Português',
        titel='StartWork – Registre horas no Jira pelo iPhone',
        beschreibung='Toque num bloco, o relógio corre. Toque de novo, descreva em uma frase – registrado no Jira. Roda no seu aparelho: sem conta, sem nuvem, compra única.',
        untertitel='Horas no Jira sem complicação',
        lead='Toque num bloco – o relógio corre. Toque de novo, descreva em uma frase o que você fez – está no Jira. Sem conta, sem nuvem, nada para aprovar.',
        preis='Compra única · sem assinatura · iPhone',
        badge_alt='Baixar na App Store',
        bilder=['Blocos para seus tickets de sempre', 'O relógio correndo num relance', 'Uma frase, registrado – refinado por IA, se quiser', 'Arredondamento, modo de teste, bloqueio com Face ID'],
        saeulen=[
            ('Sem conta, sem nuvem', 'O StartWork roda no seu iPhone. Não temos servidor e não há cadastro. Suas horas vão direto para o seu próprio Jira – e para nenhum outro lugar.'),
            ('Pague uma vez', 'Uma compra. Sem assinatura, sem anúncios, sem coleta de dados, sem custos posteriores.'),
            ('Para quem cobra por hora', 'Consultores, freelancers e agências: registre no momento em que troca de tarefa, não de memória na sexta-feira.'),
        ],
        funktionen_titel='O que ele faz',
        funktionen=[
            'Blocos para seus tickets de sempre, com título buscado no Jira',
            'Adicione tickets pela chave ou colando um link do Jira',
            'Arredondamento para 5 ou 15 minutos, se sua empresa quiser',
            'Modo de teste: veja o que seria registrado antes de registrar de verdade',
            'Notificação enquanto um relógio corre, para você não esquecer',
            'Bloqueio com Face ID – um token do Jira fica no aparelho',
            'Relatório do dia para compartilhar, e os dias anteriores para a daily',
            'Opcional: refinar comentários para o cliente com IA, usando sua própria chave da Anthropic e só após consentimento expresso',
        ],
        vorab_titel='Antes de comprar',
        vorab=[
            'O StartWork precisa de uma instância Jira na qual você possa entrar com seu próprio token. Jira Cloud, Server e Data Center são compatíveis.',
            'As horas são gravadas como registro de trabalho padrão do Jira. Se sua empresa usa o Tempo com campos obrigatórios (“Work Attributes”), eles ficam vazios.',
        ],
        faq_titel='Perguntas',
        faq=[
            ('Como registro horas no Jira pelo iPhone?', 'Instale o StartWork, informe uma vez o endereço do seu Jira e um token de API e adicione seus tickets como blocos. Toque num bloco para iniciar o relógio, toque de novo para parar, escreva uma frase – o StartWork grava como registro de trabalho no ticket.'),
            ('Funciona com o Tempo?', 'Sim. O StartWork grava registros de trabalho padrão do Jira, que o Tempo lê. Campos obrigatórios do Tempo (“Work Attributes”) não são preenchidos.'),
            ('Quais versões do Jira são compatíveis?', 'Jira Cloud (login com e-mail e token de API) e também Jira Server e Data Center (token de acesso pessoal).'),
            ('O que acontece com meus dados?', 'Eles ficam no seu iPhone e vão apenas para o seu próprio Jira. Sem análises, sem rastreamento, sem conta conosco.'),
            ('É uma assinatura?', 'Não. Você paga uma vez na App Store.'),
        ],
        hilfe='Ajuda', datenschutz='Privacidade', impressum='Aviso legal', kontakt='Contato',
        marke='Jira é uma marca da Atlassian, Tempo uma marca da Tempo ehf. O StartWork não tem vínculo com essas empresas.',
        sprache='Idioma',
    ),
    'es': dict(
        hreflang='es', ordner='es/', name='Español',
        titel='StartWork – Registra tiempo en Jira desde el iPhone',
        beschreibung='Toca un mosaico, el reloj corre. Toca otra vez, descríbelo en una frase – registrado en Jira. Funciona en tu dispositivo: sin cuenta, sin nube, compra única.',
        untertitel='Tus horas en Jira, sin líos',
        lead='Toca un mosaico – el reloj corre. Toca otra vez, describe en una frase lo que hiciste – ya está en Jira. Sin cuenta, sin nube, nada que aprobar.',
        preis='2,99 € · compra única · sin suscripción · iPhone',
        badge_alt='Descargar en el App Store',
        bilder=['Mosaicos para tus tickets habituales', 'El reloj en marcha de un vistazo', 'Una frase, registrado – pulido con IA si quieres', 'Redondeo, modo de prueba, bloqueo con Face ID'],
        saeulen=[
            ('Sin cuenta, sin nube', 'StartWork funciona en tu iPhone. No tenemos servidor ni hay registro. Tu tiempo va directo a tu propio Jira – a ningún otro sitio.'),
            ('Paga una vez', 'Una compra. Sin suscripción, sin anuncios, sin recogida de datos, sin costes posteriores.'),
            ('Para quien factura por horas', 'Consultores, freelancers y agencias: registra en el momento en que cambias de tarea, no de memoria el viernes.'),
        ],
        funktionen_titel='Qué hace',
        funktionen=[
            'Mosaicos para tus tickets habituales, con el título traído de Jira',
            'Añade tickets por clave o pegando un enlace de Jira',
            'Redondeo a 5 o 15 minutos, si tu empresa lo quiere así',
            'Modo de prueba: mira qué se registraría antes de registrarlo de verdad',
            'Notificación mientras corre un reloj, para que no se te olvide',
            'Bloqueo con Face ID – en el dispositivo hay un token de Jira',
            'Informe del día para compartir, y los días anteriores para la daily',
            'Opcional: pulir comentarios para el cliente con IA, con tu propia clave de Anthropic y solo tras tu consentimiento expreso',
        ],
        vorab_titel='Antes de comprar',
        vorab=[
            'StartWork necesita una instancia de Jira en la que puedas iniciar sesión con tu propio token. Compatible con Jira Cloud, Server y Data Center.',
            'El tiempo se registra como un registro de trabajo estándar de Jira. Si tu empresa usa Tempo con campos obligatorios («Work Attributes»), quedan vacíos.',
        ],
        faq_titel='Preguntas',
        faq=[
            ('¿Cómo registro tiempo en Jira desde mi iPhone?', 'Instala StartWork, indica una vez la dirección de tu Jira y un token de API, y añade tus tickets como mosaicos. Toca un mosaico para iniciar el reloj, toca otra vez para pararlo, escribe una frase – StartWork lo guarda como registro de trabajo en el ticket.'),
            ('¿Funciona con Tempo?', 'Sí. StartWork escribe registros de trabajo estándar de Jira, que Tempo lee. Los campos obligatorios de Tempo («Work Attributes») no se rellenan.'),
            ('¿Qué versiones de Jira son compatibles?', 'Jira Cloud (inicio de sesión con correo y token de API) y también Jira Server y Data Center (token de acceso personal).'),
            ('¿Qué pasa con mis datos?', 'Se quedan en tu iPhone y van solo a tu propio Jira. Sin analítica, sin seguimiento, sin cuenta con nosotros.'),
            ('¿Es una suscripción?', 'No. Pagas una vez en el App Store.'),
        ],
        hilfe='Ayuda', datenschutz='Privacidad', impressum='Aviso legal', kontakt='Contacto',
        marke='Jira es una marca de Atlassian y Tempo una marca de Tempo ehf. StartWork no está vinculado a estas empresas.',
        sprache='Idioma',
    ),
}
